version: '3'
services:
  zookeeper:
    hostname: zookeeper
    image: confluentinc/cp-zookeeper
    ports:
      - "32181:32181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 32181
      ZOOKEEPER_TICK_TIME: 2000
  kafka:
    hostname: kafka
    image: confluentinc/cp-kafka
    ##network_mode: host
    ports:
      - "29092:29092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:32181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092
  schema:
    hostname: schema
    image: confluentinc/cp-schema-registry
    depends_on:
      - zookeeper
      - kafka
    ports:
      - "8081:8081"
    environment:
      ACCESS_CONTROL_ALLOW_ORIGIN: "*"
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: zookeeper:32181
      SCHEMA_REGISTRY_HOST_NAME: schema
      SCHEMA_REGISTRY_LISTENERS: http://schema:8081
  rest:
    hostname: rest
    image: confluentinc/cp-kafka-rest
    ports:
      - "8082:8082"
    depends_on:
      - zookeeper
      - kafka
      - schema
    environment:
      ACCESS_CONTROL_ALLOW_ORIGIN: "*"
      KAFKA_REST_ZOOKEEPER_CONNECT: zookeeper:32181
      KAFKA_REST_LISTENERS: http://rest:8082
      KAFKA_REST_SCHEMA_REGISTRY_URL: http://schema:8081
      KAFKA_REST_HOST_NAME: rest
  kafka-connect:
    hostname: connect
    image: confluentinc/cp-kafka-connect
    depends_on:
      - zookeeper
      - kafka
      - schema
      - rest
    ports:
      - "8083:8083"
    environment:
      CONNECT_BOOTSTRAP_SERVERS: kafka:29092
      CONNECT_REST_ADVERTISED_HOST_NAME: connect
      CONNECT_REST_PORT: 8083
      CONNECT_GROUP_ID: compose-connect-group
      CONNECT_CONFIG_STORAGE_TOPIC: docker-connect-configs
      CONNECT_OFFSET_STORAGE_TOPIC: docker-connect-offsets
      CONNECT_STATUS_STORAGE_TOPIC: docker-connect-status
      CONNECT_KEY_CONVERTER: io.confluent.connect.avro.AvroConverter
      CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL: http://schema:8081
      CONNECT_VALUE_CONVERTER: io.confluent.connect.avro.AvroConverter
      CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: http://schema:8081
      CONNECT_INTERNAL_KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_INTERNAL_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_ZOOKEEPER_CONNECT: zookeeper:32181
    volumes:
        - ./jars:/etc/kafka-connect/jars   # make sure link to this path for class path

  # schema-registry-ui:
  #   image: landoop/schema-registry-ui:0.9.1
  #   hostname: kafka-schema-registry-ui
  #   ports:
  #     - "8001:8000"
  #   environment:
  #     SCHEMAREGISTRY_URL: http://kafka-schema-registry:8081/
  #     PROXY: "true"
  #   depends_on:
  #     - schema

  # kafka-connect-ui:
  #     image: landoop/kafka-connect-ui:0.9.2
  #     hostname: kafka-connect-ui
  #     ports:
  #       - "8003:8000"
  #     environment:
  #       CONNECT_URL: "http://kafka-connect:8083/"
  #       PROXY: "true"
  #     depends_on:
  #       - kafka-connect



  cbdb:
    build:
      context: . # point out the path of the Dockerfile
      dockerfile: Dockerfile-CB
    ports:
        - "8091-8094:8091-8094"
        - "11207-11210:11207-11210"
        - "18091-18094:18091-18094"
    volumes:
        - ~/kafka-cb/cb_node_1:/opt/couchbase/var





