###################################################
###################################################
#																									#	
#							     ML-cassandra							      #
#																									#					
###################################################

cassandra:
  container_name: ml_cassandra
  build: .
  
  ports:
    - "7000:7000"   
    - "7001:7001"   
    - "7199:7199"               
    - "9042:9042"
    - "9160:9160"    
  volumes:
    - /dataCassandra:/var/lib/cassandra/data
